project:
  type: website
  output-dir: docs

website:
  title: "Healthyus"
  navbar:
    background: primary    
    left:
      - text: "About US"
        href: about.qmd
      - text: "Product & Service"
        href: product.qmd
      - text: "Research & Development"
        href: research.qmd
      - text: "Contact Us"
        href: contact.qmd

    right:
      - icon: github
        href: https://github.com/healthyus

format:
  html:
    theme: 
      light: slate
      dark: cosmo
    css: styles.css

editor: visual

