project:
  type: website
  output-dir: docs

website:
  title: "Healthyus"
  favicon: "images/favicon/android-chrome-256x256.png"  
  navbar:
    background: primary    
    logo: "images/favicon/android-chrome-256x256.png"
    left:
      - text: "Product & Service"
        href: product.qmd
      - text: "Research & Development"
        href: research.qmd
      - text: "About US"
        href: about.qmd
      - text: "Blog"
        href: blog.qmd        

    right:
      - icon: github
        href: https://github.com/healthyus

format:
  html:
    theme: 
      light: cosmo
      dark: slate
    css: styles.css

editor: visual

