---
title: "Members & Contact"
format: 
  html:
    code-fold: true
engine: knitr
---

::: columns
::: {.column width="47.5%"}

## Mission

Our team consists of experienced healthcare professionals who have a passion for innovation and improving patient outcomes. We believe that our technology has the potential to revolutionize the way lung cancer is diagnosed and treated. Our mission is to provide healthcare providers and patients with an accessible, accurate, and affordable solution for early lung cancer detection. We are committed to ongoing research and development, ensuring that our product remains at the forefront of medical technology.

## Core values

Our values include a commitment to patient-centered care, excellence, and innovation. We believe that every patient deserves access to the best healthcare possible, and we are dedicated to providing that. We are proud to be leading the way in early lung cancer detection, and we are excited to see the impact that our product can have on patients' lives.

:::

::: {.column width="5%"}
:::

::: {.column width="47.5%"}

## Contact

We are always happy to hear from readers, patients, healthcare providers, and researchers. If you have any questions or comments about our product, research, or blog, please don't hesitate to contact us. You can reach us by email or by using the contact form on our website. We are committed to responding to all inquiries promptly and are always happy to provide more information about our product and research.

We value feedback from our readers and are always looking for ways to improve our product and blog. If you have any suggestions or feedback on how we can improve, please don't hesitate to let us know. We are committed to providing the best possible service to our readers, patients, healthcare providers, and researchers, and your feedback is invaluable in helping us achieve this goal.

In conclusion, our website is designed to provide information and resources for anyone interested in early lung cancer detection. We believe that our product has the potential to save countless lives, and we are committed to ensuring that it is accessible to all who need it. We are dedicated to ongoing research and development, and we believe that our blog is an essential part of our mission to educate and inform. Thank you for visiting our website, and we look forward to hearing from you.

:::
:::
